---
title: "`r params$adm_name` at ADM Level `r params$adm_level` in `r params$year` "
subtitle: "test1"
params:
  df: NONE
  adm_level: 0
  adm_name: NONE
  year: 2020
  
  
execute:
  echo: false #show/hide code output
  warning: false #suppress warnings
  message: false #suppress messages
  output: true #include output of code chunks
  cache: false
  freeze: false
  
format:
  html:
    toc: true
    toc-depth: 4
    toc-location: left
    link-external-newwindow: true
    embed-resources: true
  docx: default #works but needs better formatting
  
knitr:
  opts_chunk:
    fig.width: 10
    fig.height: 8
    dev: 'png'
    fig.align: 'center'
  
editor: visual
format-links: false
fig-align: left
fig-width: 10
fig-height: 5
fig-dpi: 300
---

```{r setup, include = FALSE}
library(IPCpoputils)
library(jsonlite)
library(dplyr)
```

```{r}
# load and manipulate data to the provided parameters
df <- fromJSON(params$df,simplifyDataFrame = TRUE)
if (params$adm_level %in% unique(df$ADM_LEVEL) & params$year %in% unique(df$YR)){
  df <- df %>% filter(ADM_LEVEL == params$adm_level & YR == params$year & SEX != 'B') 
} else{
  stop("ERROR: either your adm_level given or your year does not exist")
}
```


## Population Pyramid: `r params$year`

```{r}
pyr <- plot_pyr(df, paste0("ADM",params$adm_level), params$adm_name)
pyr
```

## Choropleth Map: `r params$adm_name` `r params$year`
```{r}
plot_chlor(tanzania_adm1, df, params$adm_name, params$year, paste0("ADM",params$adm_level))
```



